#Importing and Linking all the HDL source files used in the design
import_files -library work -hdl_source hdl/DigiReaderSM.vhd
import_files -library work -hdl_source hdl/FIFO_converter_32to64b.v
import_files -library work -hdl_source hdl/REG_CTRL.v
import_files -library work -hdl_source hdl/data_ready_delay.v
import_files -library work -hdl_source hdl/data_valid_generator.v
import_files -library work -hdl_source hdl/FIFO_MEM_CNTRL.v
import_files -library work -hdl_source hdl/PATTERN_GEN_CHECKER.v
import_files -library work -hdl_source hdl/memdata_switch.v
import_files -library work -hdl_source hdl/pattern_FIFO_cntrl.v
import_files -library work -hdl_source hdl/pattern_switch.v
import_files -library work -hdl_source hdl/pulse_generator.v
import_files -library work -hdl_source hdl/SerdesRxController.vhd
import_files -library work -hdl_source hdl/SerdesTxController.vhd
import_files -library work -hdl_source hdl/SerdesInitializer.vhd
import_files -library work -hdl_source hdl/SerdesStatus.vhd
import_files -library work -hdl_source hdl/crc_ver.v
import_files -library work -hdl_source hdl/DTC_simulator.v
import_files -library work -hdl_source hdl/MARKER_Simulator.v
import_files -library work -hdl_source hdl/mux_xcvr.v													 
import_files -library work -hdl_source hdl/EWMaker.vhd
import_files -library work -hdl_source hdl/TWIMaster.vhd
import_files -library work -hdl_source hdl/Registers.vhd
import_files -library work -hdl_source hdl/TVS_Cntrl.v
import_files -library work -hdl_source hdl/counter32.v
import_files -library work -hdl_source hdl/BusyMonitor.v
import_files -library work -hdl_source hdl/Clk_40Mhz_RisingEdgeOnly.vhd
import_files -library work -hdl_source hdl/syn_fifo.vhd
import_files -library work -hdl_source hdl/sync_ram.vhd
import_files -library work -hdl_source hdl/algorithm_constants.vhd
import_files -library work -hdl_source hdl/DracMonitor.vhd
import_files -library work -hdl_source hdl/MainResetController_0.vhd
import_files -library work -hdl_source hdl/INV_20bit.vhd
import_files -library work -hdl_source hdl/ReplyPktDecoder.v
import_files -library work -hdl_source hdl/XCVR_Reset_Controller.vhd
import_files -library work -hdl_source hdl/mux_rxout.v
import_files -library work -hdl_source hdl/crc.vhd
import_files -library work -hdl_source hdl/CommandHandler.vhd
import_files -library work -hdl_source hdl/ForwardDetector.vhd
import_files -library work -hdl_source hdl/PacketSender.vhd
import_files -library work -hdl_source hdl/TimeStamp_IF_TEST.vhd
import_files -library work -hdl_source hdl/TimeStampManager.vhd
import_files -library work -hdl_source hdl/pulse_stretcher.v
