#Importing and Linking all the HDL source files used in the design
import_files -library work -hdl_source hdl/FIFO_converter_32to64b.v
import_files -library work -hdl_source hdl/REG_CTRL.v
import_files -library work -hdl_source hdl/AXI4DMA_INIT.v
import_files -library work -hdl_source hdl/counter32.v
import_files -library work -hdl_source hdl/data_valid_generator.v
import_files -library work -hdl_source hdl/FIFO_MEM_CNTRL.v
import_files -library work -hdl_source hdl/PATTERN_GEN_CHECKER.v
import_files -library work -hdl_source hdl/pulse_generator.v
import_files -library work -hdl_source hdl/DIGISERDES_Controller.vhd
import_files -library work -hdl_source hdl/serdesmux.vhd
import_files -library work -hdl_source hdl/SerdesRxController.vhd
import_files -library work -hdl_source hdl/EWMaker.vhd
import_files -library work -hdl_source hdl/TWIMaster.vhd
import_files -library work -hdl_source hdl/Registers.vhd
import_files -library work -hdl_source hdl/TVS_Cntrl.v
import_files -library work -hdl_source hdl/Clk_40Mhz_RisingEdgeOnly.vhd
import_files -library work -hdl_source hdl/algorithm_constants.vhd
import_files -library work -hdl_source hdl/DebuggerPacketSender.vhd
import_files -library work -hdl_source hdl/DebugLatchCounter.vhd
import_files -library work -hdl_source hdl/ForwardDetector.vhd
import_files -library work -hdl_source hdl/PacketSender.vhd
import_files -library work -hdl_source hdl/MainResetController_0.vhd
import_files -library work -hdl_source hdl/ROCMonitor.vhd
import_files -library work -hdl_source hdl/INV_20bit.vhd
import_files -library work -hdl_source hdl/XCVR_Reset_Controller.vhd
import_files -library work -hdl_source hdl/crc.vhd
import_files -library work -hdl_source hdl/CommandHandler.vhd
import_files -library work -hdl_source hdl/TimeStamp_IF_TEST.vhd
import_files -library work -hdl_source hdl/TimeStampManager.vhd
