#Importing and Linking all the HDL source files used in the design
import_files -library work -hdl_source hdl/RxController.vhd
import_files -library work -hdl_source hdl/algorithm_constants.vhd
import_files -library work -hdl_source hdl/TxController.vhd
import_files -library work -hdl_source hdl/ROCFIFOController.vhd
import_files -library work -hdl_source hdl/edge_generator.v
import_files -library work -hdl_source hdl/EWMaker.vhd
import_files -library work -hdl_source hdl/EW_FIFO_controller.v
import_files -library work -hdl_source hdl/ew_size_store_and_fetch_controller.vhd
import_files -library work -hdl_source hdl/ewtag_cntrl.v
import_files -library work -hdl_source hdl/clus_pattern_cntrl.v
import_files -library work -hdl_source hdl/clus_pattern_sim.v
import_files -library work -hdl_source hdl/MUX_DIGI_DATA.v
import_files -library work -hdl_source hdl/rocfifo_cntrl.v
import_files -library work -hdl_source hdl/hit_ram.vhd
import_files -library work -hdl_source hdl/pattern_switch.v
import_files -library work -hdl_source hdl/DCSRegisters.vhd
import_files -library work -hdl_source hdl/TWIController.vhd
import_files -library work -hdl_source hdl/Registers.vhd
import_files -library work -hdl_source hdl/LeakMux.vhd
import_files -library work -hdl_source hdl/TVS_Cntrl.v
import_files -library work -hdl_source hdl/counter32.v
import_files -library work -hdl_source hdl/DCSProcessor.vhd
import_files -library work -hdl_source hdl/DCSReadCMDProcessor.vhd
import_files -library work -hdl_source hdl/DCSWriteCMDProcessor.vhd
import_files -library work -hdl_source hdl/DRACRegisters.vhd
import_files -library work -hdl_source hdl/DREQProcessor.vhd
import_files -library work -hdl_source hdl/DataStatusProcessor.vhd
import_files -library work -hdl_source hdl/ErrorCounter.vhd
import_files -library work -hdl_source hdl/delay_sreg_1bit.vhd
import_files -library work -hdl_source hdl/pulse_time_crossing.v
import_files -library work -hdl_source hdl/PBRS_checker.v
import_files -library work -hdl_source hdl/PRBS_generator.v
import_files -library work -hdl_source hdl/RxPacketReader.vhd
import_files -library work -hdl_source hdl/TxPacketWriter.vhd
import_files -library work -hdl_source hdl/ClockAligner.vhd
import_files -library work -hdl_source hdl/MUX_TX.v
import_files -library work -hdl_source hdl/WordAligner.vhd
import_files -library work -hdl_source hdl/WordFlipper.vhd
import_files -library work -hdl_source hdl/crc.vhd
import_files -library work -hdl_source hdl/req_err_switch.v
import_files -library work -hdl_source hdl/counter_16bit.v
import_files -library work -hdl_source hdl/pulse_stretcher.v
import_files -library work -hdl_source hdl/tracker_params.vh
