#set_false_path -from [ get_pins { TOP_SERDES_0/ForwardDetector_0/fifo_rst/CLK } ]
set_clock_latency -source -rise -late -5 [ get_clocks { PF_CCC_C1_0/PF_CCC_C1_0/pll_inst_0/OUT0 } ]
set_clock_latency -source -rise -early -5 [ get_clocks { PF_CCC_C1_0/PF_CCC_C1_0/pll_inst_0/OUT0 } ]
set_clock_latency -source -fall -late -5 [ get_clocks { PF_CCC_C1_0/PF_CCC_C1_0/pll_inst_0/OUT0 } ]
set_clock_latency -source -fall -early -5 [ get_clocks { PF_CCC_C1_0/PF_CCC_C1_0/pll_inst_0/OUT0 } ]
set_clock_latency -source -rise -late -5 [ get_clocks { PF_CCC_C1_1/PF_CCC_C1_0/pll_inst_0/OUT0 } ]
set_clock_latency -source -rise -early -5 [ get_clocks { PF_CCC_C1_1/PF_CCC_C1_0/pll_inst_0/OUT0 } ]
set_clock_latency -source -fall -late -5 [ get_clocks { PF_CCC_C1_1/PF_CCC_C1_0/pll_inst_0/OUT0 } ]
set_clock_latency -source -fall -early -5 [ get_clocks { PF_CCC_C1_1/PF_CCC_C1_0/pll_inst_0/OUT0 } ]
